# ── mise toolchain & environment ───────────────────────────────
# Sourced by the top-level zshrc

# PATH to the mise binary (~/.local/bin is added by dot-files/.zshrc, but
# only AFTER this file is sourced, so add it here)
export PATH="$HOME/.local/bin:$PATH"

# Completions (generated by clean-install-zsh.sh)
[[ -d "$HOME/.local/share/mise/completions" ]] && \
  fpath=("$HOME/.local/share/mise/completions" $fpath)

# PATH-based activation: sets tool versions + JAVA_HOME on cd/prompt
(( $+commands[mise] )) && eval "$(mise activate zsh)"

# Auto-create mise.toml sourcing .envrc (direnv replacement) — the file is
# left untrusted on purpose: `mise trust` is the consent step, so a cloned
# repo's .envrc is never sourced without the user saying yes. Reminds on
# every cd until trust is granted (hook-env's own WARN only fires once per
# session; its exit code — 1 while the config is untrusted — does not).
_mise_bootstrap_envrc() {
  (( $+commands[mise] )) || return 0
  [[ -f .envrc ]] || return 0
  if [[ ! -f mise.toml ]]; then
    cat > mise.toml <<'EOF'
# Auto-generated by mise.zsh to source this project's .envrc
[env]
_.source = { path = ".envrc", tools = true, redact = true }
EOF
    echo "mise: created mise.toml to source this project's .envrc"
  elif ! grep -q "Auto-generated by mise.zsh" mise.toml; then
    return 0
  fi
  mise hook-env -s zsh >/dev/null 2>&1 || \
    echo "mise: run 'mise trust' to apply this project's .envrc"
}

# Auto-install missing tool versions on directory change — mise's
# activation hook does NOT install missing tools (verified). Gated on the
# active config being trusted: `mise install` auto-trusts even with
# --dry-run-code, which would silently grant consent for the .envrc
# bootstrap file (verified v2026.8.14).
_mise_auto_install() {
  (( $+commands[mise] )) || return 0
  mise hook-env -s zsh >/dev/null 2>&1 || return 0
  mise install --dry-run-code >/dev/null 2>&1 || {
    echo "mise: Missing tool versions detected. Installing..."
    mise install
  }
}

typeset -gaU chpwd_functions
chpwd_functions=(_mise_bootstrap_envrc _mise_auto_install)

# Run on initial shell startup (asdf.zsh did the same)
_mise_bootstrap_envrc
_mise_auto_install
